### ISSUE TITLE
假开源？假开源？假开源？假开源？假开源？

### ISSUE THREAD

**Issue by SoftwareKing** [rustfs/rustfs#8]
如图标题假开源？

**Comment by loverustfs** [comment]
Each product has its own release plan.
We responded in another issue that we will release it in February or March 2025.

**Comment by loverustfs** [comment]
China is very fast, but we need more patience to ensure that the software is more robust.

**Comment by crazyYG** [comment]
> 如图标题假开源？

怎么假了？展开说说，我觉得你连代码都看不懂！张嘴就逼逼
